### ISSUE TITLE
mention current implementations of ASDF

### ISSUE THREAD

**Issue by sbinet** [spacetelescope/asdf-standard#113]
the `asdf-standard` repo (and its `read-the-doc` counterpart) should probably mention the current (known) `ASDF` implementations:

- [pyasdf](https://github.com/spacetelescope/pyasdf)
- [astrogo/asdf](https://github.com/astrogo/asdf) (shameless plug of my still WIP package, written in [Go](https://golang.org))

**Comment by mdboom** [comment]
There is an "implementations" section here:

https://asdf-standard.readthedocs.org/en/latest/intro.html#implementations

But I wasn't aware of your Go implementation.  Great news.  I can add that, or feel free to submit a pull request.

**Comment by mdboom** [comment]
Just a heads up: I'll go ahead and add this.  No need for a PR from you.

**Comment by sbinet** [comment]
ok. (I was about to do it.)

I must say I have had (still have) a few difficulties with the very dynamic nature of the `Tree` layout (especially the `ndarray` part)
do you envision a `C/C++` version of `asdf`?

**Comment by mdboom** [comment]
We've investigated a C and C++ implementation (C++ with a C wrapper probably making the most sense), but were sort of waiting for someone to say "I'll use ASDF if there were a C/C++ implementation" before devoting the resources.

Can you elaborate on the issues you are having?  (Probably in a new issue since it's a bit OT for this one...)

**Comment by embray** [comment]
@sbinet Very cool that you're working on this--I've yet to have the opportunity to do anything with Go, so let me know if there's anything I can do to help with your implementation.
