### ISSUE TITLE
ndarray: implementation issues for astrogo/asdf

### ISSUE THREAD

**Issue by sbinet** [spacetelescope/asdf-standard#115]
while implementing (still working on it) the decoding of the `tree` section of the `asdf` file format, I hit a couple of issues:
- first off, and not related to `asdf` per se, the support of tags and anchors for `YAML-1.1` is spotty in the main pure-Go `YAML` library (I had to work around go-yaml/yaml#74 with this gnarly [hack](https://github.com/astrogo/asdf/blob/5bbaa6399da6ecc2dfdebcb9dca4614b72a378f0/reader.go#L70))
- automatically generating a set of Go types from the complete set of `asdf` schema would be nice (and seems possible)
- except when there are many choices for a field's type such as in the [ndarray schema](http://asdf-standard.readthedocs.org/en/latest/schemas/stsci.edu/asdf/core/ndarray-0.1.0.html)

an `ndarray` `datatype` value can be either a `scalar-type` or an array of either a `scalar-type` or ndarray-like objects.
Modelling a `datatype` type in Go's type system doesn't look very easy right off the bat (and for many fields of my first stab at a schema data model, I just resorted to a plain `void*` equivalent (spelled `interface{}` in Go) which will force the user to apply "ugly" type casts.)
It may just very well be that an `asdf` Tree is a bit too dynamic for Go's type system or that coming up with a nice Go API is more work than a couple of hours worth of thinking about it :)
That's why I was wondering whether a C/C++ library was considered: I would have checked its API against mine.

There is a final issue I am wrestling with:
- collecting all extra key/values which are not in the top-level [core/asdf](http://asdf-standard.readthedocs.org/en/latest/schemas/stsci.edu/asdf/core/asdf-0.1.0.html) schema as a list of key/ndarrays.
  This may again be just a limitation of Go's `YAML` library, but folding these extra ndarrays as, say, a list of `NdArrays` under an `Extra` field in "my" `core.ASDF` top-level schema type, sounds difficult in `go-yaml`.

I haven't tried actually decoding an `asdf.Block` section according to an `asdf.ndarray` specification from the `Tree` so I don't know whether the encoding/decoding is straightforward or whether there are some reliance on `numpy.array` implementation details.

(but implementing a pure-Go decoder for the low-level bits of an `asdf` file was waaaay easier than for `hdf5` - even if a bit more difficult than for `FITS`)

**Comment by mdboom** [comment]
**A good fraction of what I say below is based on reading about Go for a few hours a few years ago, so please pardon my ignorance.**

@sbinet wrote:
> first off, and not related to asdf per se, the support of tags and anchors for YAML-1.1 is spotty in the main pure-Go YAML library (I had to work around go-yaml/yaml#74 with this gnarly hack)

That's unfortunate.  ASDF relies pretty heavily on tags, but anchors are pretty optional to the design (though obviously, files may contain them, so they should be supported).

> automatically generating a set of Go types from the complete set of asdf schema would be nice (and seems possible)

For pyasdf, we didn't really generate the types from the schemas so much as write converters to/from the appropriate types that exist in third-party libraries.  For example, `ndarray` converts to/from a Numpy array since that's the standard n-dimensional array type for Python.  `time` uses `astropy.time` etc.  So there aren't really types that exist specifically for ASDF alone (there's a few, but just for metadata really).

> except when there are many choices for a field's type such as in the ndarray schema

I can see how that's where the bias toward dynamic programming languages and their standard "variant" collection types has drifted in there.  But on the other hand, we are using YAML and that is how the YAML/JSON data model works.  I think limiting that flexibility would actually be fighting against what using YAML gives us in the first place.

When I was verifying the design of ASDF and its suitability for multiple languages, I did consider more static languages like C and C++.  There, I found libraries like `libvariant` that parse the YAML into variant data types, much like what happens in JavaScript/Python etc., so I didn't see this flexibility as a problem, even in less flexible languages.  It seems that yaml-go works quite differently, and it seems to be more about marshaling/unmarshaling static data types than supporting the YAML data model.  (i.e. not really for parsing arbitrary YAML, more as a marshalling tool for Go).

> an ndarray datatype value can be either a scalar-type or an array of either a scalar-type or ndarray-like objects.

You can think of a datatype as C struct (with a special case that it can be a single scalar).  Like C structs, they can be nested with other structs and fixed-length arrays.  The tricky bit in a less dynamic language is dealing with that dynamically based on what's in the file and not having to hard code it.

> Modelling a datatype type in Go's type system doesn't look very easy right off the bat (and for many fields of my first stab at a schema data model, I just resorted to a plain void* equivalent (spelled interface{} in Go) which will force the user to apply "ugly" type casts.)

Again, not being an expert in Go, that may be the best you can do.  It's certainly the best one could do in C, though in C++ you could use templates to define the datatype (assuming you knew what it should be at compile time).  When I first looked at Go, I have to say I found its lack of generics (templates) surprising and limiting for exactly this reason.

> It may just very well be that an asdf Tree is a bit too dynamic for Go's type system or that coming up with a nice Go API is more work than a couple of hours worth of thinking about it :)

It definitely is inspired by the Python/Ruby/JavaScript model of having variant datatypes at its root.  That doesn't mean it's impossible to support in something like Go -- it may just mean those variant types need to be implemented.  I definitely would look at the C++ libvariant for some inspiration there.

> collecting all extra key/values which are not in the top-level core/asdf schema as a list of key/ndarrays. This may again be just a limitation of Go's YAML library, but folding these extra ndarrays as, say, a list of NdArrays under an Extra field in "my" core.ASDF top-level schema type, sounds difficult in go-yaml.

I think, as you say, this falls out from the same issues as above.  A proper variant mapping and list type would solve that.

> I haven't tried actually decoding an asdf.Block section according to an asdf.ndarray specification from the Tree so I don't know whether the encoding/decoding is straightforward or whether there are some reliance on numpy.array implementation details.

Hopefully not -- ignoring compression for now, the memory layout is just raw binary and the alignment and ordering are defined by the `strides` keyword, or standard non-aligned C ordering if the `strides` keyword is missing.  But there is sort of an assumption that a multiarray library is available.  I wonder if Go has such a thing that could be used for this purpose.  C++ has `boost::multiarray` (and a bunch of others) for example.  Python has Numpy, of course.  It's a tricky wheel to invent, so avoid reinventing if possible.

> (but implementing a pure-Go decoder for the low-level bits of an asdf file was waaaay easier than for hdf5 - even if a bit more difficult than for FITS)

Well, that was the goal (to remain simpler than HDF5).  I hope that's still the case despite all this ;)

**Comment by embray** [comment]
> Modelling a datatype type in Go's type system doesn't look very easy right off the bat (and for many fields of my first stab at a schema data model, I just resorted to a plain void* equivalent (spelled interface{} in Go) which will force the user to apply "ugly" type casts.)

Incidentally, this is more or less how Numpy handles general structured datatypes--it actually has a type called "void", so-named after `void*`.  A void array has fixed-size elements of arbitrary size (including 0), so the stride for elements of that array are just determined by the size of whatever "void" type is attached to it.  When returning an element of the array it is wrapped in a "void" object which just has a `char*` to the data.  However, if the "void" has a structured dtype attached to it, it can use the information from the descriptor for that dtype to read the individual fields out of the char data using the appropriate offsets.  Definitely a pain to implement but not otherwise terribly fancy...

**Comment by embray** [comment]
Seems like go-yaml/yaml#74 is something that really should be fixed for proper implementation of the standard.  Fortunately it looks like an actively developed project.  Maybe we can supply a fix at some point.

**Comment by sbinet** [comment]
yes, I am relatively confident go-yaml can be improved to handle the asdf use case.
at least it can already read the whole asdf-tree (modulo that annoying yaml-1.1/yaml-1.2 tag discrepancy): all I would need to do is to come up with a not completely unfriendly interface.
ATM, I suppose it's just (design) work on my side :)

**Comment by embray** [comment]
I'm currently pretty busy with other things, but as soon as I get a break I'll be pretty interested to start taking a closer look at your code and see if there's any place we can help :)  Thanks again for your feedback and work on this!

**Comment by sbinet** [comment]
no worries. I am also a bit swamped with LSST work right now (until mid-october)

**Comment by drdavella** [comment]
Closing since this issue is quite out of date and only relevant to a particular (and probably defunct) implementation.
