### ISSUE TITLE
Complex number representation in YAML

### ISSUE THREAD

**Issue by eschnett** [spacetelescope/asdf-standard#162]
The standard defines the YAML complex number representation to be of the form `1+2i`, without surrounding parentheses. The test file `complex.yaml` surrounds some complex numbers with parentheses. Which is correct?

I also see that the regex given in the standard does not allow for `inf` or `nan`.

The standard seems to allow the form `-1+-2i`, which is disallowed by the regex.

Can you clarify?

**Comment by drdavella** [comment]
The situation with parentheses appears to be an artifact of the way that Python represents complex numbers as strings, and the way that JSON Schema treats regular expressions. Unfortunately, in order to provide backwards compatibility, it looks like I may actually have to modify the standard to explicitly allow the existence of parentheses surrounding complex numbers.

Also, I don't believe the form `-1+-2i` should be allowed, so the documentation will need to be modified.

Thanks for pointing out these issues.

**Comment by drdavella** [comment]
After digging into this more, it's clear that the current regex is not quite correct, and as a result it is not at all useful for its intended purpose. The fact that no anchors are explicitly given means that a wide variety of garbage strings will be inadvertently validated. This will need to be fixed, but I'm afraid that the result will be a very ugly regex indeed.

**Comment by eschnett** [comment]
If you define such a regex, please also make explicit which captured groups contain the real and the imaginary part.

Maybe it would be cleaner to define the syntax in terms of a grammar? That would be easier to understand, and thus to get correct. It should be possible to derive a regex (semi-)automatically from a grammar.

**Comment by drdavella** [comment]
Yes, maybe a grammar would be more expressive and easier to understand. However, I'm not sure whether there's a standard way to do that since [BNF](https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form) describes context-free grammars. I suppose a regex can be described using BNF, though.

Automatic conversion would be pretty cool, but I'm not aware of any ways to do that. It might be a fun project though...
